#!/usr/bin/env bash
# Install nginx on your web-01 server

# Update package list
sudo apt-get -y update

# Install nginx
sudo apt-get install -y nginx

ufw allow 'Nginx HTTP'

# Set up the default page
echo "Hello World!" > /var/www/html/index.html

# Restart nginx (without using systemctl)
sudo service nginx restart
