#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.


sudo apt-get update
sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '/server_name _;/a \\n    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }\n' /etc/nginx/sites-enabled/default


sudo service nginx restart
