#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.


sudo apt-get update
sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html


sed -i 's/server_name _;/server_name _;\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-enabled/default

# restart nginx
sudo service nginx restart
