#!/usr/bin/env bash
# Install nginx on your web-01 server

# Update package list
sudo apt-get -y update

# Install nginx
sudo apt-get install -y nginx

# Allow Nginx HTTP through firewall
sudo ufw allow 'Nginx HTTP'

# Set up the default page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure redirection
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default


# Restart Nginx to apply changes
sudo service nginx restart

