#!/usr/bin/env bash
# Install nginx on your web-01 server

# Update package list
sudo apt-get -y update

# Install nginx
sudo apt-get install -y nginx

ufw allow 'Nginx HTTP'

# Set up the default page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sed -i 's/server_name _;/server_name _;\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;\n\terror_page 404 \/404.html;\n\tlocation \/404.html{\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/' /etc/nginx/sites-enabled/defaul

# Restart nginx (without using systemctl)
sudo service nginx restart
