#!/usr/bin/env bash
# Configure an Ubuntu machine to have a custom header X-Served-By

# Update package information
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Create simple HTML files
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Hello ALX" | sudo tee /var/www/html/404.html

# Create Nginx configuration snippet for custom header
new_config='server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    add_header X-Served-By $hostname;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}'

# Update Nginx configuration
echo "$new_config" | sudo tee /etc/nginx/sites-available/default

# Enable the new configuration by creating a symlink
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart

