#!/usr/bin/env bash
# The file /etc/passwd has already been covered in a previous project 
# and you should be familiar with it. Today we will make up a story based on it.

file=/etc/passwd
while IFS= read -r line;do
	username=$(echo "$line" | cut -d':' -f1)
	group_id=$(echo "$line" | cut -d':' -f4)
	home_directory=$(echo "$line" | cut -d':' -f6)
	command_shell=$(echo "$line" | cut -d':' -f7)
	user_id=$(echo "$line" | cut -d':' -f3)
	passcode=$(echo "$line" | cut -d':' -f2)
	user_id_info=$(echo "$line" | cut -d':' -f5)
	echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $command_shell. $user_id's place is protected by the passcode $passcode, more info about the user here: $user_id_info"

done < $file
