#!/usr/bin/env bash
# Install ufw (Uncomplicated Firewall)

# Update package Info
sudo apt update -y

# Install ufw
sudo apt install ufw

# Enable ufw
sudo ufw enable

# Set default policies
set ufw default deny incoming
set ufw default allow outgoing

# Allow ssh (port 22)
sudo ufw allow 22/tcp

# Allow HTTPS (port 443)
sudo ufw allow 443/tcp

# Allow HTTP (port 80)
sudo ufw allow 80/tcp

