#!/usr/bin/env bash

sudo apt update
sudo apt install apache2 -y
sudo service apache2 start

sed -i 's/Listen 80/Listen 8080/' /etc/apache2/ports.conf

sed -i 's/<VirtualHost \*:80>/<VirtualHost \*:8080>/' /etc/apache2/sites-available/000-default.conf

echo 'Hello Holberton' | sudo tee /var/www/html/index.html

sudo service apache2 restart
